# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar  # replacement for deprecated exportloopref
    - gocritic
    - godot
    - gosec
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - unconvert
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Don't check blank identifier assignments like _, _ =
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - (io.Closer).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment

  goimports:
    local-prefixes: github.com/homindolenern/goapps-costing-v1

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam  # Allow large parameter structs for command pattern

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked
      - G115  # Integer overflow - safe in our pagination context

  revive:
    rules:
      - name: blank-imports
        disabled: true  # Allow blank imports for side effects
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    # Allow unused parameters in handler methods (interface compliance)
    - path: _handler\.go
      linters:
        - unparam
    # Allow unchecked errors in repository reconstitution
    - path: _repository\.go
      linters:
        - errcheck
    # Allow unchecked errors in main.go for http/shutdown
    - path: main\.go
      linters:
        - errcheck
        - contextcheck  # shutdown context intentionally uses new context
    # Allow error checks in tests
    - path: _test\.go
      linters:
        - errcheck
        - goimports  # test import grouping less strict
    # Allow integer overflow in handlers (safe pagination)
    - path: _handler\.go
      linters:
        - gosec
    # Allow unchecked errors in http delivery
    - path: internal/delivery/http/
      linters:
        - errcheck
    # Allow unchecked errors in cache (intentional)
    - path: internal/infrastructure/cache/
      linters:
        - errcheck

