# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocritic
    - godot
    - gosec
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  goimports:
    local-prefixes: github.com/homindolenern/goapps-costing-v1

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    # Allow unused parameters in handler methods (interface compliance)
    - path: _handler\.go
      linters:
        - unparam
    # Allow magic numbers in tests
    - path: _test\.go
      linters:
        - gomnd
    # Allow error checks in tests
    - path: _test\.go
      linters:
        - errcheck
